set(PROJECT_NAME_ "FOC")

set(CMAKE_BUILD_TYPE Debug)

SET(CMAKE_VERBOSE_MAKEFILE OFF)

SET(OUTPUT_ELF_NAME "demo")

ADD_DEFINITIONS(
    -DUSE_STDPERIPH_DRIVER
    -DSTM32
    -DSTM32F429_439xx
    -DHSE_VALUE=8000000
    -DCMAKE_DEMO
    -DUSING_NON_RTOS=0 # 不使用 RTOS
    -DUSING_FREERTOS=1 # 使用 FreeRTOS
    -DUSING_THREADX=2 # 使用 Threadx
    -DUSING_RTOS=USING_NON_RTOS # 选择使用的 RTOS
)